# Generated by Django 4.2.6 on 2023-11-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidohub_app', '0003_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogWalker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('about', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='about',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
