# Generated by Django 4.2.6 on 2023-11-26 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fidohub_app', '0004_dogwalker_dog_about_dog_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
