# Generated by Django 4.2.6 on 2023-11-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidohub_app', '0005_remove_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogwalker',
            name='about',
            field=models.CharField(max_length=200),
        ),
    ]
