# Generated by Django 4.2.6 on 2023-11-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidohub_app', '0006_alter_dogwalker_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_image',
            field=models.ImageField(default='static/images/defaultdog.jpg', upload_to='images/'),
        ),
    ]
