# Generated by Django 4.2.6 on 2023-11-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidohub_app', '0008_alter_dog_dog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
