# Generated by Django 4.2.6 on 2023-11-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidohub_app', '0010_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
